---
# Example usage:
# ansible-playbook -i inventory argocd_setup_example.yaml -e k8s_kubeconfig=<pathtokubeconfig>
- name: install argocd
  hosts: localhost
  gather_facts: False

  pre_tasks:

    - name: fail when no token has been provided
      fail:
        msg: "'k8s_kubeconfig' has to be provided in order to login to ocp"
      when: k8s_kubeconfig is not defined

  roles:
    - role: jeichler.argocd_ocp.argocd_setup
      vars:
        argocd_groups:
        - name: argoadmins
          permission: admin
          users:
            - jeichler
            - robot-admin
        - name: argousers
          permission: readonly
          users:
            - foobar

